x-pegasus:
  apiLang: python
  createdBy: renettej
  createdOn: 07-22-24T14:42:38Z
pegasus: '5.0'
name: ghubex1_MATLAB_build_workflow_renettej
replicaCatalog:
  replicas:
  - lfn: receive_lunch_items.m
    pfns:
    - site: local
      pfn: /home/theghub/renettej/AAA_notebooks/ghubex1/src/MATLAB/receive_lunch_items.m
  - lfn: consume_lunch_items.m
    pfns:
    - site: local
      pfn: /home/theghub/renettej/AAA_notebooks/ghubex1/src/MATLAB/consume_lunch_items.m
transformationCatalog:
  transformations:
  - name: MATLABBuild
    sites:
    - name: local
      pfn: /home/theghub/renettej/AAA_notebooks/ghubex1/remotebin/MATLAB/MATLAB_Launch.sh
      type: stageable
      arch: x86_64
      os.type: linux
      os.release: rhel
jobs:
- type: job
  name: MATLABBuild
  id: ID0000001
  arguments: []
  uses:
  - lfn: receive_lunch_items
    type: output
    stageOut: true
    registerReplica: false
  - lfn: receive_lunch_items.m
    type: input
  - lfn: consume_lunch_items
    type: output
    stageOut: true
    registerReplica: false
  - lfn: consume_lunch_items.m
    type: input
  metadata:
    time: '30'
jobDependencies: []
